eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka,http://eureka:eureka@localhost:8762/eureka
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
