eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:eureka@172.17.0.4:8761/eureka
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
