ribbon: 
  #ConnectTimeout: 3000
  #ReadTimeout: 60000
  #maxAutoRetries: 1
  #MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
    
zuul:
  prefix: /test
  routes:
    ignoredService: '*'
    HelloService:
      path: /demo/**
      serviceId: HelloService
      stripPrefix: true
    #merchant-service:
    #  path: /merchants/**
    #  serviceId: merchant-service
    #  stripPrefix: true
