ribbon: 
  ConnectTimeout: 3000
  ReadTimeout: 60000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
    
zuul:
  routes:
    ignoredService: '*'
    demo-service:
      path: /api/demo/**
      serviceId: demo-service
      servicePath: /demo/all
      stripPrefix: false
    #merchant-service:
    #  path: /merchants/**
    #  serviceId: merchant-service
    #  stripPrefix: true
