ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000
zuul:
  routes:
    ignoredService: '*'
    invoice-service:
      path: /invoices/**
      serviceId: invoice-service
      stripPrefix: false
    merchant-service:
      path: /merchants/**
      serviceId: merchant-service
      stripPrefix: true
