management:
  context-path: /admin
    
zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    hello-services:
      path: /greeting/**
      serviceId: HELLO-SERVICES
      stripPrefix: false
    microservice:
      path: /estado/**
      serviceId: MICROSERVICE
      stripPrefix: false
     
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds : 60000 

ribbon:
  eureka:
    enabled: true   
  eager-load:
      enabled: true
