management:
  context-path: /admin
    
zuul:
  #prefix: /api
  routes:
    ignoredService: '*'
    #oauth2:
    #  path: /uaa/**
    #  serviceId: OAUTH-SERVER
    #  stripPrefix: false
    hello-services:
      path: /greeting/**
      serviceId: HELLO-SERVICES
      #stripPrefix: true
