ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000
zuul:
  routes:
    ignoredService: '*'
    demo-service:
      path: /invoices/**
      serviceId: demo-service
      stripPrefix: false
    #merchant-service:
    #  path: /merchants/**
    #  serviceId: merchant-service
    #  stripPrefix: true
