management:
  context-path: /admin
    
zuul:
  prefix: /api
  ignoredService: '*'
  routes:
    hello-services:
      path: /greeting/**
      serviceId: HELLO-SERVICES
      #stripPrefix: true
     
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds : 60000 

ribbon:
  eureka:
    enabled: true    
  ConnectTimeout : 3000 
  ReadTimeout : 60000
